ALTER TABLE Page ADD COLUMN customSchema TEXT;
ALTER TABLE Page ADD COLUMN schemaEnabled INTEGER DEFAULT 0;
ALTER TABLE Page ADD COLUMN schemaUpdatedAt DATETIME;
ALTER TABLE Page ADD COLUMN schemaUpdatedBy TEXT;
ALTER TABLE Page ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP;
